# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import immvis_pb2 as immvis__pb2

class ImmVisJupyterStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.PlotDataset = channel.unary_unary(
        '/ImmVisJupyter/PlotDataset',
        request_serializer=immvis__pb2.DatasetToPlot.SerializeToString,
        response_deserializer=immvis__pb2.Empty.FromString,
        )


class ImmVisJupyterServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def PlotDataset(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ImmVisJupyterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'PlotDataset': grpc.unary_unary_rpc_method_handler(
          servicer.PlotDataset,
          request_deserializer=immvis__pb2.DatasetToPlot.FromString,
          response_serializer=immvis__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ImmVisJupyter', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
