# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: immvis.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='immvis.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cimmvis.proto\"\x07\n\x05\x45mpty\"*\n\rDatasetToPlot\x12\x19\n\x04rows\x18\x01 \x03(\x0b\x32\x0b.DatasetRow\"\x1f\n\nDatasetRow\x12\x11\n\trowValues\x18\x01 \x03(\x02\x32\x38\n\rImmVisJupyter\x12\'\n\x0bPlotDataset\x12\x0e.DatasetToPlot\x1a\x06.Empty\"\x00\x62\x06proto3')
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=23,
)


_DATASETTOPLOT = _descriptor.Descriptor(
  name='DatasetToPlot',
  full_name='DatasetToPlot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rows', full_name='DatasetToPlot.rows', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=67,
)


_DATASETROW = _descriptor.Descriptor(
  name='DatasetRow',
  full_name='DatasetRow',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rowValues', full_name='DatasetRow.rowValues', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=100,
)

_DATASETTOPLOT.fields_by_name['rows'].message_type = _DATASETROW
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['DatasetToPlot'] = _DATASETTOPLOT
DESCRIPTOR.message_types_by_name['DatasetRow'] = _DATASETROW
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'immvis_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

DatasetToPlot = _reflection.GeneratedProtocolMessageType('DatasetToPlot', (_message.Message,), {
  'DESCRIPTOR' : _DATASETTOPLOT,
  '__module__' : 'immvis_pb2'
  # @@protoc_insertion_point(class_scope:DatasetToPlot)
  })
_sym_db.RegisterMessage(DatasetToPlot)

DatasetRow = _reflection.GeneratedProtocolMessageType('DatasetRow', (_message.Message,), {
  'DESCRIPTOR' : _DATASETROW,
  '__module__' : 'immvis_pb2'
  # @@protoc_insertion_point(class_scope:DatasetRow)
  })
_sym_db.RegisterMessage(DatasetRow)



_IMMVISJUPYTER = _descriptor.ServiceDescriptor(
  name='ImmVisJupyter',
  full_name='ImmVisJupyter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=102,
  serialized_end=158,
  methods=[
  _descriptor.MethodDescriptor(
    name='PlotDataset',
    full_name='ImmVisJupyter.PlotDataset',
    index=0,
    containing_service=None,
    input_type=_DATASETTOPLOT,
    output_type=_EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IMMVISJUPYTER)

DESCRIPTOR.services_by_name['ImmVisJupyter'] = _IMMVISJUPYTER

# @@protoc_insertion_point(module_scope)
